### ISSUE TITLE
Catalog search not working

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis-lifelines#109]
When searched for CHDEVEL4A no results where found, biut there is an item named CHDEVEL4A
![screen shot 2014-08-11 at 15 25 03](https://cloud.githubusercontent.com/assets/116559/3876321/24147f04-215b-11e4-9a05-7fa0f42a055e.png)
![screen shot 2014-08-11 at 15 25 40](https://cloud.githubusercontent.com/assets/116559/3876322/25f48cb0-215b-11e4-8490-4387f5e7fc37.png)

**Comment by jjettenn** [comment]
Not found during testing
